sudo: false # routes build to the container-based infrastructure for a faster build
language: ruby
rvm:
  - 2.4.1

cache: bundler

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/deploy.sh

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
    - COMMIT_AUTHOR_EMAIL: "webmaster@cubingusa.org"
    - ENCRYPTION_LABEL: "689ba5a2b3c6"
